packages:
  - packages/*

allowBuilds:
  better-sqlite3: true
  cpu-features: false
  esbuild: false
  oracledb: false
  protobufjs: false
  ssh2: false



overrides:
  toml@<4.1.2: ^4.1.2
  toml@<4.2.0: ^4.2.0
