CREATE OR REPLACE TABLE users (
  id NUMBER(38,0) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE posts (
  id NUMBER(38,0) PRIMARY KEY,
  user_id NUMBER(38,0) REFERENCES users(id),
  title VARCHAR(200) NOT NULL,
  content VARCHAR,
  published BOOLEAN DEFAULT FALSE,
  views NUMBER(38,0) DEFAULT 0,
  published_at TIMESTAMP_NTZ
);
